services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=financialdb
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - db
    networks:
      - financial-microservices
volumes:
  pgdata:
    driver: local
  keycloak_data:
    driver: local

networks:
  financial-microservices:
    driver: bridge