services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=financialdb
volumes:
  pgdata:
    driver: local
networks:
  financial-microservices:
    driver: bridge